"""pequena alteracao na coluna 'paginas'

Revision ID: 305c5f6157a5
Revises: 1c9cd7a23a1f
Create Date: 2025-03-29 20:53:03.074214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305c5f6157a5'
down_revision = '1c9cd7a23a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.alter_column('paginas',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.alter_column('paginas',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
